### ISSUE TITLE
공유하기에 링크가 있으면 어떻까요?

### ISSUE THREAD

**Issue by hijae** [belorin/belorin.github.io#1]
한국어 프로젝트에는 종류가 많고 검색하기 어려운데 공유하기를 누르면 자동으로 링크가 나오면 좋지 않을까요?
원본에는 없지만 있으면 편할 것 같아요.

**Comment by belorin** [comment]
저도 고려를 해보았는데, 요즘 보통 주소가 쓰여지면 미리보기가 나타나는등 지져분해지는 면이 있어서 고려 중입니다. 공유를 강제하고 싶지는 않아 고민이 됩니다.

**Comment by lens0021** [comment]
추가해 주신 것 같아서 이슈 닫아주셔도 괜찮겠습니다~~
